name: scipy18jlab
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow=0.12.1=py36_2
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py_0
  - binaryornot=0.4.4=py36_0
  - bleach=2.1.3=py_0
  - bqplot=0.10.1=py36_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - clangdev=6.0.0=default_0
  - click=6.7=py_1
  - cloudpickle=0.5.3=py_0
  - cookiecutter=1.6.0=py36_0
  - cryptography=2.2.1=py36_0
  - cycler=0.10.0=py36_0
  - dask-core=0.18.1=py_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1
  - future=0.16.0=py36_0
  - html5lib=1.0.1=py_0
  - idna=2.7=py36_0
  - imageio=2.3.0=py36_0
  - ipydatawidgets=3.1.0=py_1
  - ipykernel=4.8.2=py36_0
  - ipyscales=0.2.2=py_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipyvolume=0.4.5=py36_0
  - ipywebrtc=0.3.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jinja2-time=0.2.0=py36_1
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.32.1=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - kiwisolver=1.0.1=py36_1
  - libpng=1.6.34=0
  - llvm-meta=6.0.0=0
  - llvmdev=6.0.0=default_3
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py36_1
  - nbformat=4.4.0=py36_0
  - networkx=2.1=py36_0
  - nodejs=9.11.1=0
  - notebook=5.5.0=py36_0
  - olefile=0.45.1=py36_0
  - pandas=0.23.1=py36_0
  - parso=0.2.1=py_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.1.0=py36_0
  - poyo=0.4.1=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - pygments=2.2.0=py36_0
  - pycparser=2.18=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pysocks=1.6.8=py36_1
  - python=3.6.5=1
  - python-dateutil=2.7.3=py_0
  - pythreejs=1.1.0=py36_2
  - pytz=2018.4=py_0
  - pywavelets=0.5.2=py36_1
  - pyzmq=17.0.0=py36_4
  - requests=2.19.1=py36_0
  - scikit-image=0.14.0=py36hfc679d8_1
  - send2trash=1.5.0=py_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - traittypes=0.2.1=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.31.0=py36_0
  - whichcraft=0.4.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.3=0
  - zeromq=4.2.5=1
  - numpy=1.14.3
  - pip=10.0.1=py36_0
  - scipy=1.1.0
  - pip:
    - dask==0.18.1
