name: pycon2019
channels:
  - conda-forge
dependencies:
  - python=3.7
  - aiohttp
  - trio
  - pip
  - cookiecutter=1.6
  - notebook=5.7
  - pandas=0.24
  - nodejs=9.11
  - jupyterlab
  - bqplot
  - pythreejs
  - line_profiler
  - matplotlib
  - rpy2
  - simplegeneric
  - cython
  - pillow
